plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-teaching-cs.github.io 
baseurl: "/w20"  
github_url: https://github.com/ucsb-teaching-cs/w20

title: "UCSB Teaching CS"
course: "CS190J"
qtr: "W20"
quarter: "Winter 2020"
ta_list: ""
ta_list_full: ""
instructor: "Mirza"


start_week: 1
start_date: 2020-01-05 
num_weeks: 10
extra_exam_week: true


cal_dates: >
  [
  {"label":"First Day of Instruction", "date":"2020-01-06" },
  {"label":"MLK Jr. Day", "date":"2020-01-20" , "holiday":true },
  {"label":"President's Day", "date":"2020-02-17" , "holiday":true },
  {"label":"No lecture: Professor attending SIGCSE Conference", "date":"2020-03-12" , "holiday":true },
  {"label":"Drop deadline (no W grade)","date":"2020-02-03" },
  {"label":"Instruction Ends", "date":"2020-03-13" },

  ]

kramdown:
   parse_block_html: true
   default_lang: python


exclude:
   - vendor
include:
   - _pages

timezone: America/Los_Angeles

collections:
  papers:
    output: true
    permalink: /hwk/:path/
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


