plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-teaching-cs.github.io 
baseurl: "/w20"  
github_url: https://github.com/ucsb-teaching-cs/w20

title: "UCSB Teaching CS"
course: "CS190J"
qtr: "W20"
quarter: "Winter 2020"
ta_list: ""
ta_list_full: ""
instructor: "Mirza"


start_week: 1
start_date: 2019-09-22 
num_weeks: 11
extra_exam_week: true


cal_dates: >
  [
  {"label":"First day of Fall Quarter", "date":"2019-09-26" },
  {"label":"Univ Holiday: Veterans' Day", "date":"2019-11-11" },
  {"label":"Univ Holiday: Thanksgiving Break", "date":"2019-11-28" },
  {"label":"Univ Holiday: Thanksgiving Break", "date":"2019-11-29" },
  {"label":"Last day of instruction", "date":"2019-12-06" },
  {"label":"Finals Begin", "date":"2019-12-07" },
  {"label":"Finals End", "date":"2019-12-13" },
  {"label":"Last day to drop (11pm)", "date":"2019-10-23" }
  ]

kramdown:
   parse_block_html: true
   default_lang: python


exclude:
   - vendor
include:
   - _pages

timezone: America/Los_Angeles

collections:
  papers:
    output: true
    permalink: /hwk/:path/
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


